[package]
name = "noise_gate"
version = "0.1.0"
edition = "2021"
exculde = ["data/*"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dasp = "0.11.0"

[dev-dependencies]
hound = "3.4.0"
structopt = "0.3.3"